name: CI

on:
  push:
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: rustup component add rustfmt clippy

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets

      - name: Build Documentation
        run: cargo doc --no-deps

      - name: Run tests
        run: cargo test

  minimum-supported-rust-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo +1.61.0 check --locked --lib
